# Generated by Django 5.1.6 on 2025-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('usuario', '0005_remove_usuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='lideres',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
    ]
