# Generated by Django 5.1.6 on 2025-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamento_lideres'),
        ('usuario', '0005_remove_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='lideres',
            field=models.ManyToManyField(related_name='departamentos_liderados', to='usuario.usuario'),
        ),
    ]
