# Generated by Django 5.2.8 on 2025-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_lideres'),
        ('usuario', '0005_remove_usuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='departamentos', to='usuario.usuario'),
        ),
    ]
