# Generated by Django 5.1.6 on 2025-11-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_departamento_lideres'),
        ('usuario', '0005_remove_usuario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateTimeField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aberto', max_length=15)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_departamento', to='departamento.departamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_funcionario', to='usuario.usuario')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_lider', to='usuario.usuario')),
            ],
        ),
    ]
