# Generated by Django 5.1.6 on 2025-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='tipo',
            field=models.CharField(choices=[('correcao', 'Correção'), ('melhoria', 'Melhoria'), ('implementacao', 'Implementação')], default='correcao', max_length=20),
        ),
    ]
