# Generated by Django 5.2.8 on 2025-11-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('adm', 'Administrador'), ('func', 'Funcionário'), ('lid', 'Líder')], max_length=4)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='atv', max_length=4)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
