# Generated by Django 5.2.8 on 2025-11-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
