# Generated by Django 5.2.8 on 2025-11-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('atv', 'Ativo'), ('inat', 'Inativo')], default='atv', max_length=4),
        ),
    ]
