# Generated by Django 5.1.6 on 2025-11-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
    ]
